/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GPT_Back_Forth_Two_Agent;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
